// <auto-generated> Modelo criado manualmente para representar a tabela Analises. </auto-generated>
#nullable disable
using System;
using System.Text.Json;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Analises
{
    public long Id { get; set; }

    public int RespostaId { get; set; }

    public JsonDocument Analytics { get; set; }

    public JsonDocument Keywords { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Respostas Resposta { get; set; }
}
