// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Anexos
{
    public int Anexoid { get; set; }

    public int Pesquisaid { get; set; }

    public string Nome { get; set; }

    public string Extensao { get; set; }

    public int? Perguntaid { get; set; }

    public string Nomeoriginal { get; set; }

    public string Contenttype { get; set; }

    public long? Tamanhobytes { get; set; }

    public string Base64data { get; set; }

    public virtual Perguntas Pergunta { get; set; }

    public virtual Pesquisas Pesquisa { get; set; }

    public virtual ICollection<Respostas> Resposta { get; set; } = new List<Respostas>();
}