// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Anexos
{
    public int AnexoId { get; set; }

    public int PesquisaId { get; set; }

    public string Nome { get; set; }

    public string Extensao { get; set; }

    public int? PerguntaId { get; set; }

    public string NomeOriginal { get; set; }

    public string ContentType { get; set; }

    public long? TamanhoBytes { get; set; }

    public string Base64Data { get; set; }

    public virtual Perguntas Pergunta { get; set; }

    public virtual Pesquisas Pesquisa { get; set; }

    public virtual ICollection<Respostas> Resposta { get; set; } = new List<Respostas>();
}