// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class anexos
{
    public int anexoid { get; set; }

    public int pesquisaid { get; set; }

    public string nome { get; set; }

    public string extensao { get; set; }

    public int? perguntaid { get; set; }

    public string nomeoriginal { get; set; }

    public string contenttype { get; set; }

    public long? tamanhobytes { get; set; }

    public string base64data { get; set; }

    public virtual perguntas pergunta { get; set; }

    public virtual pesquisas pesquisa { get; set; }

    public virtual ICollection<respostas> resposta { get; set; } = new List<respostas>();

    public virtual ICollection<respostas_anexos> respostas_anexos { get; set; } = new List<respostas_anexos>();
}