// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Blocklist
{
    public int Id { get; set; }

    public string IPAddress { get; set; }

    public string UserAgent { get; set; }

    public string Motivo { get; set; }

    public DateTime? CriadoEm { get; set; }
}