// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Externallogins
{
    public int Externalloginid { get; set; }

    public int Loginid { get; set; }

    public string Provider { get; set; }

    public string Provideruserid { get; set; }

    public DateTime Criadoem { get; set; }

    public virtual Login Login { get; set; }
}