// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class ExternalLogins
{
    public int ExternalLoginId { get; set; }

    public int LoginId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual Login Login { get; set; }
}