// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class FastSurveyContext : DbContext
{
    public FastSurveyContext()
    {
    }

    public FastSurveyContext(DbContextOptions<FastSurveyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Anexos> Anexos { get; set; }

    public virtual DbSet<Login> Login { get; set; }

    public virtual DbSet<Opcoespergunta> Opcoespergunta { get; set; }

    public virtual DbSet<Pastas> Pastas { get; set; }

    public virtual DbSet<Perguntas> Perguntas { get; set; }

    public virtual DbSet<Pesquisas> Pesquisas { get; set; }

    public virtual DbSet<Respostas> Respostas { get; set; }

    public virtual DbSet<Tipopergunta> Tipopergunta { get; set; }

    public virtual DbSet<Tipopesquisa> Tipopesquisa { get; set; }

    public virtual DbSet<Tipousuario> Tipousuario { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Persist Security Info=True;Username=postgres;Password=admin;Host=localhost;Database=FastSurvey");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Anexos>(entity =>
        {
            entity.HasKey(e => e.Anexoid).HasName("anexos_pkey");

            entity.ToTable("anexos");

            entity.HasIndex(e => e.Perguntaid, "idx_anexos_perguntaid");

            entity.HasIndex(e => e.Pesquisaid, "idx_anexos_pesquisaid");

            entity.Property(e => e.Anexoid).HasColumnName("anexoid");
            entity.Property(e => e.Base64data).HasColumnName("base64data");
            entity.Property(e => e.Contenttype)
                .HasMaxLength(150)
                .HasColumnName("contenttype");
            entity.Property(e => e.Extensao)
                .IsRequired()
                .HasMaxLength(25)
                .HasColumnName("extensao");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nome");
            entity.Property(e => e.Nomeoriginal)
                .HasMaxLength(255)
                .HasColumnName("nomeoriginal");
            entity.Property(e => e.Perguntaid).HasColumnName("perguntaid");
            entity.Property(e => e.Pesquisaid).HasColumnName("pesquisaid");
            entity.Property(e => e.Tamanhobytes).HasColumnName("tamanhobytes");

            entity.HasOne(d => d.Pergunta).WithMany(p => p.Anexos)
                .HasForeignKey(d => d.Perguntaid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("anexos_perguntaid_fkey");

            entity.HasOne(d => d.Pesquisa).WithMany(p => p.Anexos)
                .HasForeignKey(d => d.Pesquisaid)
                .HasConstraintName("anexos_pesquisaid_fkey");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.HasKey(e => e.Loginid).HasName("login_pkey");

            entity.ToTable("login");

            entity.HasIndex(e => e.Email, "uq_login_email").IsUnique();

            entity.Property(e => e.Loginid).HasColumnName("loginid");
            entity.Property(e => e.Dataregistro)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("dataregistro");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Senha)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("senha");
            entity.Property(e => e.Tipousuarioid).HasColumnName("tipousuarioid");
            entity.Property(e => e.Tipousuariotexto)
                .HasMaxLength(50)
                .HasColumnName("tipousuariotexto");
            entity.Property(e => e.Usuario)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("usuario");

            entity.HasOne(d => d.Tipousuario).WithMany(p => p.Login)
                .HasForeignKey(d => d.Tipousuarioid)
                .HasConstraintName("fk_login_tipousuarioid");
        });

        modelBuilder.Entity<Opcoespergunta>(entity =>
        {
            entity.HasKey(e => e.Opcaoid).HasName("opcoespergunta_pkey");

            entity.ToTable("opcoespergunta");

            entity.HasIndex(e => e.Perguntaid, "idx_opcoespergunta_perguntaid");

            entity.HasIndex(e => new { e.Perguntaid, e.Texto }, "ux_opcoespergunta_perguntaid_texto").IsUnique();

            entity.Property(e => e.Opcaoid).HasColumnName("opcaoid");
            entity.Property(e => e.Ativa)
                .HasDefaultValue(true)
                .HasColumnName("ativa");
            entity.Property(e => e.Correta)
                .HasDefaultValue(false)
                .HasColumnName("correta");
            entity.Property(e => e.Ordem)
                .HasDefaultValue(0)
                .HasColumnName("ordem");
            entity.Property(e => e.Perguntaid).HasColumnName("perguntaid");
            entity.Property(e => e.Texto)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("texto");

            entity.HasOne(d => d.Pergunta).WithMany(p => p.Opcoespergunta)
                .HasForeignKey(d => d.Perguntaid)
                .HasConstraintName("opcoespergunta_perguntaid_fkey");
        });

        modelBuilder.Entity<Pastas>(entity =>
        {
            entity.HasKey(e => e.Pastaid).HasName("pastas_pkey");

            entity.ToTable("pastas");

            entity.HasIndex(e => new { e.Loginid, e.Nome }, "uq_pastas_loginid_nome").IsUnique();

            entity.Property(e => e.Pastaid).HasColumnName("pastaid");
            entity.Property(e => e.Loginid).HasColumnName("loginid");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nome");

            entity.HasOne(d => d.Login).WithMany(p => p.Pastas)
                .HasForeignKey(d => d.Loginid)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_pastas_loginid");
        });

        modelBuilder.Entity<Perguntas>(entity =>
        {
            entity.HasKey(e => e.Perguntaid).HasName("perguntas_pkey");

            entity.ToTable("perguntas");

            entity.HasIndex(e => e.Ordem, "idx_perguntas_ordem");

            entity.HasIndex(e => e.Pesquisaid, "idx_perguntas_pesquisaid");

            entity.HasIndex(e => e.Tipoperguntaid, "idx_perguntas_tipoperguntaid");

            entity.Property(e => e.Perguntaid).HasColumnName("perguntaid");
            entity.Property(e => e.Ordem)
                .HasDefaultValue(0)
                .HasColumnName("ordem");
            entity.Property(e => e.Permitemultiplaselecao)
                .HasDefaultValue(false)
                .HasColumnName("permitemultiplaselecao");
            entity.Property(e => e.Pesquisaid).HasColumnName("pesquisaid");
            entity.Property(e => e.Temgabarito)
                .HasDefaultValue(false)
                .HasColumnName("temgabarito");
            entity.Property(e => e.Texto)
                .IsRequired()
                .HasColumnName("texto");
            entity.Property(e => e.Tipoperguntaid).HasColumnName("tipoperguntaid");

            entity.HasOne(d => d.Pesquisa).WithMany(p => p.Perguntas)
                .HasForeignKey(d => d.Pesquisaid)
                .HasConstraintName("perguntas_pesquisaid_fkey");

            entity.HasOne(d => d.Tipopergunta).WithMany(p => p.Perguntas)
                .HasForeignKey(d => d.Tipoperguntaid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("perguntas_tipoperguntaid_fkey");
        });

        modelBuilder.Entity<Pesquisas>(entity =>
        {
            entity.HasKey(e => e.Pesquisaid).HasName("pesquisas_pkey");

            entity.ToTable("pesquisas");

            entity.HasIndex(e => e.Datacriacao, "idx_pesquisas_datacriacao");

            entity.HasIndex(e => e.Descricao, "idx_pesquisas_descricao");

            entity.HasIndex(e => e.Loginid, "idx_pesquisas_loginid");

            entity.HasIndex(e => e.Pastaid, "idx_pesquisas_pastaid");

            entity.HasIndex(e => e.Tipopesquisaid, "idx_pesquisas_tipopesquisa");

            entity.HasIndex(e => e.Titulo, "idx_pesquisas_titulo");

            entity.Property(e => e.Pesquisaid).HasColumnName("pesquisaid");
            entity.Property(e => e.Dataatualizacao).HasColumnName("dataatualizacao");
            entity.Property(e => e.Datacriacao)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("datacriacao");
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("descricao");
            entity.Property(e => e.Loginid).HasColumnName("loginid");
            entity.Property(e => e.Pastaid).HasColumnName("pastaid");
            entity.Property(e => e.Qrcodeurl).HasColumnName("qrcodeurl");
            entity.Property(e => e.Templatejson)
                .HasDefaultValueSql("'[]'::text")
                .HasColumnName("templatejson");
            entity.Property(e => e.Tipopesquisaid).HasColumnName("tipopesquisaid");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("titulo");

            entity.HasOne(d => d.Login).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.Loginid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_pesquisas_loginid");

            entity.HasOne(d => d.Pasta).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.Pastaid)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("pesquisas_pastaid_fkey");

            entity.HasOne(d => d.Tipopesquisa).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.Tipopesquisaid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pesquisas_tipopesquisaid_fkey");
        });

        modelBuilder.Entity<Respostas>(entity =>
        {
            entity.HasKey(e => e.Respostaid).HasName("respostas_pkey");

            entity.ToTable("respostas");

            entity.HasIndex(e => e.Dataresposta, "idx_respostas_dataresposta");

            entity.HasIndex(e => e.Perguntaid, "idx_respostas_perguntaid");

            entity.Property(e => e.Respostaid).HasColumnName("respostaid");
            entity.Property(e => e.Dataresposta)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("dataresposta");
            entity.Property(e => e.Perguntaid).HasColumnName("perguntaid");
            entity.Property(e => e.Texto)
                .IsRequired()
                .HasColumnName("texto");

            entity.HasOne(d => d.Pergunta).WithMany(p => p.Respostas)
                .HasForeignKey(d => d.Perguntaid)
                .HasConstraintName("respostas_perguntaid_fkey");

            entity.HasMany(d => d.Anexo).WithMany(p => p.Resposta)
                .UsingEntity<Dictionary<string, object>>(
                    "RespostasAnexos",
                    r => r.HasOne<Anexos>().WithMany()
                        .HasForeignKey("Anexoid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("respostas_anexos_anexoid_fkey"),
                    l => l.HasOne<Respostas>().WithMany()
                        .HasForeignKey("Respostaid")
                        .HasConstraintName("respostas_anexos_respostaid_fkey"),
                    j =>
                    {
                        j.HasKey("Respostaid", "Anexoid").HasName("respostas_anexos_pkey");
                        j.ToTable("respostas_anexos");
                        j.HasIndex(new[] { "Anexoid" }, "idx_respostas_anexos_anexoid");
                        j.IndexerProperty<int>("Respostaid").HasColumnName("respostaid");
                        j.IndexerProperty<int>("Anexoid").HasColumnName("anexoid");
                    });

            entity.HasMany(d => d.Opcao).WithMany(p => p.Resposta)
                .UsingEntity<Dictionary<string, object>>(
                    "RespostasOpcoes",
                    r => r.HasOne<Opcoespergunta>().WithMany()
                        .HasForeignKey("Opcaoid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("respostas_opcoes_opcaoid_fkey"),
                    l => l.HasOne<Respostas>().WithMany()
                        .HasForeignKey("Respostaid")
                        .HasConstraintName("respostas_opcoes_respostaid_fkey"),
                    j =>
                    {
                        j.HasKey("Respostaid", "Opcaoid").HasName("respostas_opcoes_pkey");
                        j.ToTable("respostas_opcoes");
                        j.HasIndex(new[] { "Opcaoid" }, "idx_respostasopcoes_opcaoid");
                        j.HasIndex(new[] { "Respostaid" }, "idx_respostasopcoes_respostaid");
                        j.IndexerProperty<int>("Respostaid").HasColumnName("respostaid");
                        j.IndexerProperty<int>("Opcaoid").HasColumnName("opcaoid");
                    });
        });

        modelBuilder.Entity<Tipopergunta>(entity =>
        {
            entity.HasKey(e => e.Tipoperguntaid).HasName("tipopergunta_pkey");

            entity.ToTable("tipopergunta");

            entity.Property(e => e.Tipoperguntaid).HasColumnName("tipoperguntaid");
            entity.Property(e => e.Desabilitado)
                .HasDefaultValue(false)
                .HasColumnName("desabilitado");
            entity.Property(e => e.Tipopergunta1)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("tipopergunta");
        });

        modelBuilder.Entity<Tipopesquisa>(entity =>
        {
            entity.HasKey(e => e.Tipopesquisaid).HasName("tipopesquisa_pkey");

            entity.ToTable("tipopesquisa");

            entity.Property(e => e.Tipopesquisaid).HasColumnName("tipopesquisaid");
            entity.Property(e => e.Desabilitado)
                .HasDefaultValue(false)
                .HasColumnName("desabilitado");
            entity.Property(e => e.Tipopesquisa1)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("tipopesquisa");
        });

        modelBuilder.Entity<Tipousuario>(entity =>
        {
            entity.HasKey(e => e.Tipousuarioid).HasName("tipousuario_pkey");

            entity.ToTable("tipousuario");

            entity.Property(e => e.Tipousuarioid).HasColumnName("tipousuarioid");
            entity.Property(e => e.Tipousuario1)
                .HasMaxLength(50)
                .HasColumnName("tipousuario");
        });

        modelBuilder.Entity<Tokens>(entity =>
        {
            entity.HasKey(e => e.Tokenid).HasName("tokens_pkey");

            entity.ToTable("tokens");

            entity.HasIndex(e => e.Token, "uq_tokens_token").IsUnique();

            entity.Property(e => e.Tokenid).HasColumnName("tokenid");
            entity.Property(e => e.Dataexpirado)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("dataexpirado");
            entity.Property(e => e.Dataregistro)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("dataregistro");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnName("token");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}