// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class FastSurveyContext : DbContext
{
    public FastSurveyContext()
    {
    }

    public FastSurveyContext(DbContextOptions<FastSurveyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Anexos> Anexos { get; set; }

    public virtual DbSet<ExternalLogins> ExternalLogins { get; set; }

    public virtual DbSet<Login> Login { get; set; }

    public virtual DbSet<LoginAvatar> LoginAvatar { get; set; }

    public virtual DbSet<OpcoesPergunta> OpcoesPergunta { get; set; }

    public virtual DbSet<ParticipantesSessao> ParticipantesSessao { get; set; }

    public virtual DbSet<Pastas> Pastas { get; set; }

    public virtual DbSet<Perguntas> Perguntas { get; set; }

    public virtual DbSet<Pesquisas> Pesquisas { get; set; }

    public virtual DbSet<Respostas> Respostas { get; set; }

    public virtual DbSet<SessoesInterativas> SessoesInterativas { get; set; }

    public virtual DbSet<TipoPergunta> TipoPergunta { get; set; }

    public virtual DbSet<TipoPesquisa> TipoPesquisa { get; set; }

    public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Persist Security Info=True;Username=postgres;Password=admin;Host=localhost;Database=FastSurvey");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Anexos>(entity =>
        {
            entity.HasKey(e => e.AnexoId).HasName("anexos_pkey");

            entity.HasIndex(e => e.PerguntaId, "idx_anexos_perguntaid");

            entity.HasIndex(e => e.PesquisaId, "idx_anexos_pesquisaid");

            entity.Property(e => e.AnexoId).HasDefaultValueSql("nextval('anexos_anexoid_seq'::regclass)");
            entity.Property(e => e.ContentType).HasMaxLength(150);
            entity.Property(e => e.Extensao)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NomeOriginal).HasMaxLength(255);

            entity.HasOne(d => d.Pergunta).WithMany(p => p.Anexos)
                .HasForeignKey(d => d.PerguntaId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("anexos_perguntaid_fkey");

            entity.HasOne(d => d.Pesquisa).WithMany(p => p.Anexos)
                .HasForeignKey(d => d.PesquisaId)
                .HasConstraintName("anexos_pesquisaid_fkey");
        });

        modelBuilder.Entity<ExternalLogins>(entity =>
        {
            entity.HasKey(e => e.ExternalLoginId).HasName("externallogins_pkey");

            entity.HasIndex(e => e.LoginId, "idx_externallogins_loginid");

            entity.HasIndex(e => new { e.Provider, e.ProviderUserId }, "uq_provider_user").IsUnique();

            entity.Property(e => e.ExternalLoginId).HasDefaultValueSql("nextval('externallogins_externalloginid_seq'::regclass)");
            entity.Property(e => e.CriadoEm).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProviderUserId)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Login).WithMany(p => p.ExternalLogins)
                .HasForeignKey(d => d.LoginId)
                .HasConstraintName("fk_externallogins_loginid");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("login_pkey");

            entity.HasIndex(e => e.Email, "uq_login_email").IsUnique();

            entity.Property(e => e.LoginId).HasDefaultValueSql("nextval('login_loginid_seq'::regclass)");
            entity.Property(e => e.DataRegistro).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.EmailConfirmado).HasDefaultValue(false);
            entity.Property(e => e.Senha)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TipoUsuarioId).HasDefaultValue(13);
            entity.Property(e => e.TipoUsuarioTexto).HasMaxLength(50);
            entity.Property(e => e.Usuario)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.TipoUsuario).WithMany(p => p.Login)
                .HasForeignKey(d => d.TipoUsuarioId)
                .HasConstraintName("FkLoginTipoUsuarioId");
        });

        modelBuilder.Entity<LoginAvatar>(entity =>
        {
            entity.HasKey(e => e.AvatarId).HasName("loginavatar_pkey");

            entity.HasIndex(e => e.LoginId, "idx_loginavatar_loginid");

            entity.HasIndex(e => e.LoginId, "uq_loginavatar_loginid").IsUnique();

            entity.Property(e => e.AvatarId).HasDefaultValueSql("nextval('loginavatar_avatarid_seq'::regclass)");
            entity.Property(e => e.ContentType).HasMaxLength(150);
            entity.Property(e => e.CriadoEm).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.NomeOriginal).HasMaxLength(255);
            entity.Property(e => e.Versao).HasDefaultValue(0);

            entity.HasOne(d => d.Login).WithOne(p => p.LoginAvatar)
                .HasForeignKey<LoginAvatar>(d => d.LoginId)
                .HasConstraintName("fk_loginavatar_loginid");
        });

        modelBuilder.Entity<OpcoesPergunta>(entity =>
        {
            entity.HasKey(e => e.OpcaoId).HasName("opcoespergunta_pkey");

            entity.HasIndex(e => e.Ativa, "idx_opcoespergunta_ativa");

            entity.HasIndex(e => e.Ordem, "idx_opcoespergunta_ordem");

            entity.HasIndex(e => e.PerguntaId, "idx_opcoespergunta_perguntaid");

            entity.HasIndex(e => new { e.PerguntaId, e.Texto }, "ux_opcoespergunta_perguntaid_texto").IsUnique();

            entity.Property(e => e.OpcaoId).HasDefaultValueSql("nextval('opcoespergunta_opcaoid_seq'::regclass)");
            entity.Property(e => e.Ativa).HasDefaultValue(true);
            entity.Property(e => e.Correta).HasDefaultValue(false);
            entity.Property(e => e.Ordem).HasDefaultValue(0);
            entity.Property(e => e.Texto)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Pergunta).WithMany(p => p.OpcoesPergunta)
                .HasForeignKey(d => d.PerguntaId)
                .HasConstraintName("opcoespergunta_perguntaid_fkey");
        });

        modelBuilder.Entity<ParticipantesSessao>(entity =>
        {
            entity.HasKey(e => e.ParticipanteId).HasName("participantes_sessao_pkey");

            entity.Property(e => e.ParticipanteId).HasDefaultValueSql("nextval('participantes_sessao_participante_id_seq'::regclass)");
            entity.Property(e => e.EntrouEm).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.NomeParticipante)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SessaoId)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Sessao).WithMany(p => p.ParticipantesSessao)
                .HasForeignKey(d => d.SessaoId)
                .HasConstraintName("FkParticipantesSessao");
        });

        modelBuilder.Entity<Pastas>(entity =>
        {
            entity.HasKey(e => e.PastaId).HasName("pastas_pkey");

            entity.HasIndex(e => new { e.LoginId, e.Nome }, "uq_pastas_loginid_nome").IsUnique();

            entity.Property(e => e.PastaId).HasDefaultValueSql("nextval('pastas_pastaid_seq'::regclass)");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Login).WithMany(p => p.Pastas)
                .HasForeignKey(d => d.LoginId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_pastas_loginid");
        });

        modelBuilder.Entity<Perguntas>(entity =>
        {
            entity.HasKey(e => e.PerguntaId).HasName("perguntas_pkey");

            entity.HasIndex(e => e.Ordem, "idx_perguntas_ordem");

            entity.HasIndex(e => e.PesquisaId, "idx_perguntas_pesquisaid");

            entity.HasIndex(e => e.TipoPerguntaId, "idx_perguntas_tipoperguntaid");

            entity.Property(e => e.PerguntaId).HasDefaultValueSql("nextval('perguntas_perguntaid_seq'::regclass)");
            entity.Property(e => e.Ordem).HasDefaultValue(0);
            entity.Property(e => e.PermiteMultiplasSelecao).HasDefaultValue(false);
            entity.Property(e => e.TemGabarito).HasDefaultValue(false);
            entity.Property(e => e.Texto).IsRequired();

            entity.HasOne(d => d.Pesquisa).WithMany(p => p.Perguntas)
                .HasForeignKey(d => d.PesquisaId)
                .HasConstraintName("perguntas_pesquisaid_fkey");

            entity.HasOne(d => d.TipoPergunta).WithMany(p => p.Perguntas)
                .HasForeignKey(d => d.TipoPerguntaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("perguntas_tipoperguntaid_fkey");
        });

        modelBuilder.Entity<Pesquisas>(entity =>
        {
            entity.HasKey(e => e.PesquisaId).HasName("pesquisas_pkey");

            entity.HasIndex(e => e.Ativa, "idx_pesquisas_ativa");

            entity.HasIndex(e => e.DataCriacao, "idx_pesquisas_datacriacao");

            entity.HasIndex(e => e.DataFechamento, "idx_pesquisas_datafechamento");

            entity.HasIndex(e => e.Descricao, "idx_pesquisas_descricao");

            entity.HasIndex(e => e.IsInterativa, "idx_pesquisas_isinterativa");

            entity.HasIndex(e => e.LoginId, "idx_pesquisas_loginid");

            entity.HasIndex(e => e.PastaId, "idx_pesquisas_pastaid");

            entity.HasIndex(e => e.TipoPesquisaId, "idx_pesquisas_tipopesquisa");

            entity.HasIndex(e => e.Titulo, "idx_pesquisas_titulo");

            entity.Property(e => e.PesquisaId).HasDefaultValueSql("nextval('pesquisas_pesquisaid_seq'::regclass)");
            entity.Property(e => e.Ativa).HasDefaultValue(true);
            entity.Property(e => e.DataCriacao).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.IsInterativa).HasDefaultValue(false);
            entity.Property(e => e.PermiteRespostasAnonimas).HasDefaultValue(true);
            entity.Property(e => e.TemLimitadorTempo).HasDefaultValue(false);
            entity.Property(e => e.TemplateJson).HasDefaultValueSql("'[]'::text");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Login).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.LoginId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_pesquisas_loginid");

            entity.HasOne(d => d.Pasta).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.PastaId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("pesquisas_pastaid_fkey");

            entity.HasOne(d => d.TipoPesquisa).WithMany(p => p.Pesquisas)
                .HasForeignKey(d => d.TipoPesquisaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pesquisas_tipopesquisaid_fkey");
        });

        modelBuilder.Entity<Respostas>(entity =>
        {
            entity.HasKey(e => e.RespostaId).HasName("RespostasPkey");

            entity.HasIndex(e => e.RespostaAnonima, "IdxRespostasAnonima");

            entity.HasIndex(e => e.DataResposta, "IdxRespostasDataResposta");

            entity.HasIndex(e => e.PerguntaId, "IdxRespostasPerguntaId");

            entity.HasIndex(e => e.SessaoId, "IdxRespostasSessao");

            entity.Property(e => e.RespostaId).HasDefaultValueSql("nextval('respostas_respostaid_seq'::regclass)");
            entity.Property(e => e.DataResposta).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.RespostaAnonima).HasDefaultValue(false);
            entity.Property(e => e.SessaoId).HasMaxLength(50);
            entity.Property(e => e.Texto).IsRequired();

            entity.HasOne(d => d.Participante).WithMany(p => p.Respostas)
                .HasForeignKey(d => d.ParticipanteId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FkRespostasParticipante");

            entity.HasOne(d => d.Pergunta).WithMany(p => p.Respostas)
                .HasForeignKey(d => d.PerguntaId)
                .HasConstraintName("RespostasPerguntaIdFkey");

            entity.HasMany(d => d.Anexo).WithMany(p => p.Resposta)
                .UsingEntity<Dictionary<string, object>>(
                    "RespostasAnexos",
                    r => r.HasOne<Anexos>().WithMany()
                        .HasForeignKey("AnexoId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("RespostasAnexosAnexoIdFkey"),
                    l => l.HasOne<Respostas>().WithMany()
                        .HasForeignKey("RespostaId")
                        .HasConstraintName("RespostasAnexosRespostaIdFkey"),
                    j =>
                    {
                        j.HasKey("RespostaId", "AnexoId").HasName("RespostasAnexosPkey");
                        j.HasIndex(new[] { "AnexoId" }, "IdxRespostasAnexosAnexoId");
                    });

            entity.HasMany(d => d.Opcao).WithMany(p => p.Resposta)
                .UsingEntity<Dictionary<string, object>>(
                    "RespostasOpcoes",
                    r => r.HasOne<OpcoesPergunta>().WithMany()
                        .HasForeignKey("OpcaoId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("RespostasOpcoesOpcaoIdFkey"),
                    l => l.HasOne<Respostas>().WithMany()
                        .HasForeignKey("RespostaId")
                        .HasConstraintName("RespostasOpcoesRespostaIdFkey"),
                    j =>
                    {
                        j.HasKey("RespostaId", "OpcaoId").HasName("RespostasOpcoesPkey");
                        j.HasIndex(new[] { "OpcaoId" }, "IdxRespostasOpcoesOpcaoId");
                        j.HasIndex(new[] { "RespostaId" }, "IdxRespostasOpcoesRespostaId");
                    });
        });

        modelBuilder.Entity<SessoesInterativas>(entity =>
        {
            entity.HasKey(e => e.SessaoId).HasName("SessoesInterativasPkey");

            entity.HasIndex(e => e.Ativa, "IdxSessoesAtiva");

            entity.HasIndex(e => e.CodigoAcesso, "IdxSessoesCodigo");

            entity.HasIndex(e => e.CodigoAcesso, "UqSessoesCodigo").IsUnique();

            entity.Property(e => e.SessaoId).HasMaxLength(50);
            entity.Property(e => e.Ativa).HasDefaultValue(true);
            entity.Property(e => e.CodigoAcesso)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.CriadaEm).HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.HasOne(d => d.Pesquisa).WithMany(p => p.SessoesInterativas)
                .HasForeignKey(d => d.PesquisaId)
                .HasConstraintName("FkSessoesPesquisa");
        });

        modelBuilder.Entity<TipoPergunta>(entity =>
        {
            entity.HasKey(e => e.TipoPerguntaId).HasName("TipoPerguntaPkey");

            entity.ToTable(tb => tb.HasComment("Tipos de pergunta: 1=Discursiva, 2=Objetiva, 3=Multipla Escolha"));

            entity.Property(e => e.TipoPerguntaId).HasDefaultValueSql("nextval('tipopergunta_tipoperguntaid_seq'::regclass)");
            entity.Property(e => e.Desabilitado).HasDefaultValue(false);
            entity.Property(e => e.TipoPergunta1)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("TipoPergunta");
        });

        modelBuilder.Entity<TipoPesquisa>(entity =>
        {
            entity.HasKey(e => e.TipoPesquisaId).HasName("TipoPesquisaPkey");

            entity.ToTable(tb => tb.HasComment("Tipos de pesquisa: 1=Pesquisa de Campo, 2=Teste"));

            entity.Property(e => e.TipoPesquisaId).HasDefaultValueSql("nextval('tipopesquisa_tipopesquisaid_seq'::regclass)");
            entity.Property(e => e.Desabilitado).HasDefaultValue(false);
            entity.Property(e => e.TipoPesquisa1)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("TipoPesquisa");
        });

        modelBuilder.Entity<TipoUsuario>(entity =>
        {
            entity.HasKey(e => e.TipoUsuarioId).HasName("TipoUsuarioPkey");

            entity.ToTable(tb => tb.HasComment("Tipos de usuário: 13=Usuário, 14=Usuário Premium, 15=Administrador"));

            entity.Property(e => e.TipoUsuarioId).HasDefaultValueSql("nextval('tipousuario_tipousuarioid_seq'::regclass)");
            entity.Property(e => e.TipoUsuario1)
                .HasMaxLength(50)
                .HasColumnName("TipoUsuario");
        });

        modelBuilder.Entity<Tokens>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("TokensPkey");

            entity.HasIndex(e => e.Token, "UqTokensToken").IsUnique();

            entity.HasIndex(e => e.Token, "idx_tokens_token_validos").HasFilter("(\"UsadoEm\" IS NULL)");

            entity.HasIndex(e => new { e.LoginId, e.Finalidade }, "uq_tokens_loginid_finalidade_ativo")
                .IsUnique()
                .HasFilter("(\"UsadoEm\" IS NULL)");

            entity.Property(e => e.TokenId).HasDefaultValueSql("nextval('tokens_tokenid_seq'::regclass)");
            entity.Property(e => e.DataExpirado).HasDefaultValueSql("(CURRENT_TIMESTAMP + '24:00:00'::interval)");
            entity.Property(e => e.DataRegistro).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.Finalidade).HasMaxLength(30);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Login).WithMany(p => p.Tokens)
                .HasForeignKey(d => d.LoginId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FkTokensLoginId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}