// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class FeatureFlags
{
    public int LoginId { get; set; }

    public string Flag { get; set; }

    public bool Ativa { get; set; }

    public virtual Login Login { get; set; }
}