// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class login
{
    public int loginid { get; set; }

    public string usuario { get; set; }

    public string email { get; set; }

    public string senha { get; set; }

    public DateTime dataregistro { get; set; }

    public int? tipousuarioid { get; set; }

    public string tipousuariotexto { get; set; }

    public virtual ICollection<pesquisas> pesquisas { get; set; } = new List<pesquisas>();

    public virtual tipousuario tipousuario { get; set; }
}