// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Login
{
    public int LoginId { get; set; }

    public string Usuario { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    public DateTime DataRegistro { get; set; }

    public int? TipoUsuarioId { get; set; }

    public string TipoUsuarioTexto { get; set; }

    public bool EmailConfirmado { get; set; }

    /// <summary>
    /// Nome completo do usuário (obrigatório para Google)
    /// </summary>
    public string NomeCompleto { get; set; }

    /// <summary>
    /// Indica se o usuário aceitou os termos de uso
    /// </summary>
    public bool TermosAceitos { get; set; }

    /// <summary>
    /// Data/hora em que os termos foram aceitos
    /// </summary>
    public DateTime? DataAceiteTermos { get; set; }

    /// <summary>
    /// Indica se é o primeiro acesso do usuário
    /// </summary>
    public bool PrimeiroAcesso { get; set; }

    public virtual ICollection<ExternalLogins> ExternalLogins { get; set; } = new List<ExternalLogins>();

    public virtual ICollection<FeatureFlags> FeatureFlags { get; set; } = new List<FeatureFlags>();

    public virtual LoginAvatar LoginAvatar { get; set; }

    public virtual ICollection<Pastas> Pastas { get; set; } = new List<Pastas>();

    public virtual ICollection<Pesquisas> Pesquisas { get; set; } = new List<Pesquisas>();

    public virtual TipoUsuario TipoUsuario { get; set; }

    public virtual ICollection<Tokens> Tokens { get; set; } = new List<Tokens>();
}