// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Loginavatar
{
    public int Avatarid { get; set; }

    public int Loginid { get; set; }

    public string Storageurl { get; set; }

    public string Nomeoriginal { get; set; }

    public string Contenttype { get; set; }

    public long? Tamanhobytes { get; set; }

    public DateTime Criadoem { get; set; }

    public DateTime? Atualizadoem { get; set; }

    public int Versao { get; set; }

    public virtual Login Login { get; set; }
}