// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Login
{
    public int Loginid { get; set; }

    public string Usuario { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    public DateTime Dataregistro { get; set; }

    public int? Tipousuarioid { get; set; }

    public string Tipousuariotexto { get; set; }

    public virtual ICollection<Pastas> Pastas { get; set; } = new List<Pastas>();

    public virtual ICollection<Pesquisas> Pesquisas { get; set; } = new List<Pesquisas>();

    public virtual Tipousuario Tipousuario { get; set; }
}