// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class LoginAvatar
{
    public int AvatarId { get; set; }

    public int LoginId { get; set; }

    public string StorageUrl { get; set; }

    public string NomeOriginal { get; set; }

    public string ContentType { get; set; }

    public long? TamanhoBytes { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public int Versao { get; set; }

    /// <summary>
    /// Dados da imagem em base64 para exibição
    /// </summary>
    public string Base64Data { get; set; }

    /// <summary>
    /// Largura da imagem em pixels
    /// </summary>
    public int? Largura { get; set; }

    /// <summary>
    /// Altura da imagem em pixels
    /// </summary>
    public int? Altura { get; set; }

    /// <summary>
    /// Formato da imagem (jpg, png, etc)
    /// </summary>
    public string Formato { get; set; }

    public virtual Login Login { get; set; }
}