// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class LoginAvatar
{
    public int AvatarId { get; set; }

    public int LoginId { get; set; }

    public string StorageUrl { get; set; }

    public string NomeOriginal { get; set; }

    public string ContentType { get; set; }

    public long? TamanhoBytes { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public int Versao { get; set; }

    public virtual Login Login { get; set; }
}