// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class opcoespergunta
{
    public int opcaoid { get; set; }

    public int perguntaid { get; set; }

    public string texto { get; set; }

    public bool correta { get; set; }

    public virtual perguntas pergunta { get; set; }

    public virtual ICollection<respostas> resposta { get; set; } = new List<respostas>();

    public virtual ICollection<respostas_opcoes> respostas_opcoes { get; set; } = new List<respostas_opcoes>();
}