// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Opcoespergunta
{
    public int Opcaoid { get; set; }

    public int Perguntaid { get; set; }

    public string Texto { get; set; }

    public bool Correta { get; set; }

    public int Ordem { get; set; }

    public bool Ativa { get; set; }

    public virtual Perguntas Pergunta { get; set; }

    public virtual ICollection<Respostas> Resposta { get; set; } = new List<Respostas>();
}