// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class ParticipantesSessao
{
    public int ParticipanteId { get; set; }

    public string SessaoId { get; set; }

    public string NomeParticipante { get; set; }

    public DateTime EntrouEm { get; set; }

    public DateTime? SaiuEm { get; set; }

    /// <summary>
    /// Pontuação total do participante
    /// </summary>
    public int PontuacaoTotal { get; set; }

    /// <summary>
    /// Número de respostas corretas
    /// </summary>
    public int RespostasCorretas { get; set; }

    /// <summary>
    /// Tempo médio de resposta em segundos
    /// </summary>
    public int? TempoMedioResposta { get; set; }

    /// <summary>
    /// Posição no ranking da sessão
    /// </summary>
    public int? Ranking { get; set; }

    public virtual ICollection<Respostas> Respostas { get; set; } = new List<Respostas>();

    public virtual SessoesInterativas Sessao { get; set; }
}