// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class ParticipantesSessao
{
    public int ParticipanteId { get; set; }

    public string SessaoId { get; set; }

    public string NomeParticipante { get; set; }

    public DateTime EntrouEm { get; set; }

    public DateTime? SaiuEm { get; set; }

    /// <summary>
    /// Se o participante está ativo na sessão
    /// </summary>
    public bool Ativo { get; set; }

    public virtual ICollection<Respostas> Respostas { get; set; } = new List<Respostas>();

    public virtual SessoesInterativas Sessao { get; set; }
}