// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class pastas
{
    public int pastaid { get; set; }

    public string nome { get; set; }

    public int? loginid { get; set; }

    public virtual login login { get; set; }

    public virtual ICollection<pesquisas> pesquisas { get; set; } = new List<pesquisas>();
}