// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Pastas
{
    public int Pastaid { get; set; }

    public string Nome { get; set; }

    public int? Loginid { get; set; }

    public virtual Login Login { get; set; }

    public virtual ICollection<Pesquisas> Pesquisas { get; set; } = new List<Pesquisas>();
}