// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Perguntas
{
    public int PerguntaId { get; set; }

    public int TipoPerguntaId { get; set; }

    public int PesquisaId { get; set; }

    public string Texto { get; set; }

    public bool TemGabarito { get; set; }

    public bool PermiteMultiplasSelecao { get; set; }

    public int Ordem { get; set; }

    /// <summary>
    /// Pontuação total da pergunta
    /// </summary>
    public int PontuacaoTotal { get; set; }

    /// <summary>
    /// Tempo limite em segundos para responder
    /// </summary>
    public int? TempoLimite { get; set; }

    /// <summary>
    /// Se deve mostrar explicação após resposta
    /// </summary>
    public bool MostrarExplicacao { get; set; }

    public DateTime? DeletadoEm { get; set; }

    public virtual ICollection<Anexos> Anexos { get; set; } = new List<Anexos>();

    public virtual ICollection<OpcoesPergunta> OpcoesPergunta { get; set; } = new List<OpcoesPergunta>();

    public virtual Pesquisas Pesquisa { get; set; }

    public virtual ICollection<Respostas> Respostas { get; set; } = new List<Respostas>();

    public virtual TipoPergunta TipoPergunta { get; set; }
}