// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Perguntas
{
    public int Perguntaid { get; set; }

    public int Tipoperguntaid { get; set; }

    public int Pesquisaid { get; set; }

    public string Texto { get; set; }

    public bool Temgabarito { get; set; }

    public bool Permitemultiplaselecao { get; set; }

    public int Ordem { get; set; }

    public virtual ICollection<Anexos> Anexos { get; set; } = new List<Anexos>();

    public virtual ICollection<Opcoespergunta> Opcoespergunta { get; set; } = new List<Opcoespergunta>();

    public virtual Pesquisas Pesquisa { get; set; }

    public virtual ICollection<Respostas> Respostas { get; set; } = new List<Respostas>();

    public virtual Tipopergunta Tipopergunta { get; set; }
}