// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class perguntas
{
    public int perguntaid { get; set; }

    public int tipoperguntaid { get; set; }

    public int pesquisaid { get; set; }

    public string texto { get; set; }

    public virtual ICollection<opcoespergunta> opcoespergunta { get; set; } = new List<opcoespergunta>();

    public virtual pesquisas pesquisa { get; set; }

    public virtual ICollection<respostas> respostas { get; set; } = new List<respostas>();

    public virtual tipopergunta tipopergunta { get; set; }
}