// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class pesquisas
{
    public int pesquisaid { get; set; }

    public int loginid { get; set; }

    public int tipopesquisaid { get; set; }

    public string titulo { get; set; }

    public string descricao { get; set; }

    public string TemplateJson { get; set; }

    public virtual ICollection<anexos> anexos { get; set; } = new List<anexos>();

    public virtual login login { get; set; }

    public virtual ICollection<perguntas> perguntas { get; set; } = new List<perguntas>();

    public virtual tipopesquisa tipopesquisa { get; set; }
}