// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Pesquisas
{
    public int PesquisaId { get; set; }

    public int LoginId { get; set; }

    public int TipoPesquisaId { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public string TemplateJson { get; set; }

    public int? PastaId { get; set; }

    public DateTime DataCriacao { get; set; }

    public DateTime? DataAtualizacao { get; set; }

    public string QRCodeUrl { get; set; }

    public bool TemLimitadorTempo { get; set; }

    public DateTime? DataFechamento { get; set; }

    public bool IsInterativa { get; set; }

    public bool PermiteRespostasAnonimas { get; set; }

    public int? LimiteRespostas { get; set; }

    public bool Ativa { get; set; }

    /// <summary>
    /// Se a pesquisa requer identificação do respondente
    /// </summary>
    public bool RequerIdentificacao { get; set; }

    /// <summary>
    /// Se permite edição após publicação
    /// </summary>
    public bool PermiteEdicao { get; set; }

    /// <summary>
    /// Configurações avançadas em JSON
    /// </summary>
    public string ConfiguracaoAvancada { get; set; }

    /// <summary>
    /// URL amigável da pesquisa
    /// </summary>
    public string Slug { get; set; }

    public int Versao { get; set; }

    public string Status { get; set; }

    public int? CriadoPor { get; set; }

    public int? AtualizadoPor { get; set; }

    public virtual ICollection<Anexos> Anexos { get; set; } = new List<Anexos>();

    public virtual Login Login { get; set; }

    public virtual Pastas Pasta { get; set; }

    public virtual ICollection<Perguntas> Perguntas { get; set; } = new List<Perguntas>();

    public virtual ICollection<SessoesInterativas> SessoesInterativas { get; set; } = new List<SessoesInterativas>();

    public virtual TipoPesquisa TipoPesquisa { get; set; }
}