// <auto-generated> Manualmente adicionada para mapear a tabela PesquisasPastas. </auto-generated>
#nullable disable
using System;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class PesquisasPastas
{
    public int PesquisaId { get; set; }

    public int PastaId { get; set; }

    public DateTime VinculadaEm { get; set; }

    public virtual Pesquisas Pesquisa { get; set; }

    public virtual Pastas Pasta { get; set; }
}
