// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Pesquisas
{
    public int Pesquisaid { get; set; }

    public int Loginid { get; set; }

    public int Tipopesquisaid { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public string Templatejson { get; set; }

    public int? Pastaid { get; set; }

    public DateTime Datacriacao { get; set; }

    public DateTime? Dataatualizacao { get; set; }

    public string Qrcodeurl { get; set; }

    public bool Temlimitadortempo { get; set; }

    public DateTime? Datafechamento { get; set; }

    public bool Isinterativa { get; set; }

    public bool PermiteRespostasAnonimas { get; set; }

    public int? LimiteRespostas { get; set; }

    public bool Ativa { get; set; }

    public virtual ICollection<Anexos> Anexos { get; set; } = new List<Anexos>();

    public virtual Login Login { get; set; }

    public virtual Pastas Pasta { get; set; }

    public virtual ICollection<Perguntas> Perguntas { get; set; } = new List<Perguntas>();

    public virtual ICollection<SessoesInterativas> SessoesInterativas { get; set; } = new List<SessoesInterativas>();

    public virtual Tipopesquisa Tipopesquisa { get; set; }
}