// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Respostas
{
    public int RespostaId { get; set; }

    public int PerguntaId { get; set; }

    public string Texto { get; set; }

    public DateTime DataResposta { get; set; }

    public string SessaoId { get; set; }

    public bool RespostaAnonima { get; set; }

    public int? ParticipanteId { get; set; }

    /// <summary>
    /// Pontuação obtida na resposta
    /// </summary>
    public int PontuacaoObtida { get; set; }

    /// <summary>
    /// Tempo gasto para responder em segundos
    /// </summary>
    public int? TempoResposta { get; set; }

    /// <summary>
    /// Se a resposta está correta
    /// </summary>
    public bool? Correta { get; set; }

    /// <summary>
    /// Data/hora da correção automática
    /// </summary>
    public DateTime? DataCorrecao { get; set; }

    public string Protocolo { get; set; }

    public DateTime? RespondidaEm { get; set; }

    public string TextoResposta { get; set; }

    public virtual ParticipantesSessao Participante { get; set; }

    public virtual Perguntas Pergunta { get; set; }

    public virtual ICollection<Anexos> Anexo { get; set; } = new List<Anexos>();

    public virtual ICollection<OpcoesPergunta> Opcao { get; set; } = new List<OpcoesPergunta>();
}