// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class SessoesInterativas
{
    public string SessaoId { get; set; }

    public int PesquisaId { get; set; }

    public string CodigoAcesso { get; set; }

    public DateTime CriadaEm { get; set; }

    public DateTime? IniciadaEm { get; set; }

    public DateTime? FinalizadaEm { get; set; }

    public bool Ativa { get; set; }

    /// <summary>
    /// ID da pergunta atual sendo exibida para todos os participantes
    /// </summary>
    public int? PerguntaAtualId { get; set; }

    /// <summary>
    /// Ordem da pergunta atual (para facilitar navegação)
    /// </summary>
    public int? OrdemPerguntaAtual { get; set; }

    /// <summary>
    /// Se a sessão está em modo de apresentação (criador controla o avanço)
    /// </summary>
    public bool ModoApresentacao { get; set; }

    /// <summary>
    /// Se a pergunta atual está ativa para respostas
    /// </summary>
    public bool PerguntaAtiva { get; set; }

    public virtual ICollection<ParticipantesSessao> ParticipantesSessao { get; set; } = new List<ParticipantesSessao>();

    public virtual Perguntas PerguntaAtual { get; set; }

    public virtual Pesquisas Pesquisa { get; set; }
}