// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class SessoesInterativas
{
    public string SessaoId { get; set; }

    public int PesquisaId { get; set; }

    public string CodigoAcesso { get; set; }

    public DateTime CriadaEm { get; set; }

    public DateTime? IniciadaEm { get; set; }

    public DateTime? FinalizadaEm { get; set; }

    public bool Ativa { get; set; }

    public virtual ICollection<ParticipantesSessao> ParticipantesSessao { get; set; } = new List<ParticipantesSessao>();

    public virtual Pesquisas Pesquisa { get; set; }
}