// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class tipopesquisa
{
    public int tipopesquisaid { get; set; }

    public string tipopesquisa1 { get; set; }

    public bool desabilitado { get; set; }

    public virtual ICollection<pesquisas> pesquisas { get; set; } = new List<pesquisas>();
}