// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Tipopesquisa
{
    public int Tipopesquisaid { get; set; }

    public string Tipopesquisa1 { get; set; }

    public bool Desabilitado { get; set; }

    public virtual ICollection<Pesquisas> Pesquisas { get; set; } = new List<Pesquisas>();
}