// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

/// <summary>
/// Tipos de pergunta: 1=Discursiva, 2=Objetiva, 3=Multipla Escolha
/// </summary>
public partial class TipoPergunta
{
    public int TipoPerguntaId { get; set; }

    public string TipoPergunta1 { get; set; }

    public bool Desabilitado { get; set; }

    public virtual ICollection<Perguntas> Perguntas { get; set; } = new List<Perguntas>();
}