// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class tipopergunta
{
    public int tipoperguntaid { get; set; }

    public string tipopergunta1 { get; set; }

    public bool desabilitado { get; set; }

    public virtual ICollection<perguntas> perguntas { get; set; } = new List<perguntas>();
}