// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class tipousuario
{
    public int usuarioid { get; set; }

    public string tipousuario1 { get; set; }

    public virtual ICollection<login> login { get; set; } = new List<login>();
}