// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

/// <summary>
/// Tipos de usuário: 13=Usuário, 14=Usuário Premium, 15=Administrador
/// </summary>
public partial class TipoUsuario
{
    public int TipoUsuarioId { get; set; }

    public string TipoUsuario1 { get; set; }

    public virtual ICollection<Login> Login { get; set; } = new List<Login>();
}