// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Tipopergunta
{
    public int Tipoperguntaid { get; set; }

    public string Tipopergunta1 { get; set; }

    public bool Desabilitado { get; set; }

    public virtual ICollection<Perguntas> Perguntas { get; set; } = new List<Perguntas>();
}