// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class tokens
{
    public int tokenid { get; set; }

    public string token { get; set; }

    public DateTime dataregistro { get; set; }

    public DateTime dataexpirado { get; set; }
}