// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SISTEMA_FASTSURVEY.MODEL.Models;

public partial class Tokens
{
    public int Tokenid { get; set; }

    public string Token { get; set; }

    public DateTime Dataregistro { get; set; }

    public DateTime Dataexpirado { get; set; }

    public int? Loginid { get; set; }

    public string Finalidade { get; set; }

    public DateTime? Usadoem { get; set; }

    public virtual Login Login { get; set; }
}