// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SISTEMA_FASTSURVEY.MODEL.Models;

#nullable disable

namespace SISTEMA_FASTSURVEY.MODEL.Migrations
{
    [DbContext(typeof(FastSurveyContext))]
    partial class FastSurveyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.anexos", b =>
                {
                    b.Property<int>("anexoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("anexoid"));

                    b.Property<string>("extensao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("pesquisaid")
                        .HasColumnType("integer");

                    b.HasKey("anexoid")
                        .HasName("anexos_pkey");

                    b.HasIndex("pesquisaid");

                    b.ToTable("anexos");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.login", b =>
                {
                    b.Property<int>("loginid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("loginid"));

                    b.Property<DateTime>("dataregistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("tipousuarioid")
                        .HasColumnType("integer");

                    b.Property<string>("tipousuariotexto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("loginid")
                        .HasName("login_pkey");

                    b.HasIndex("tipousuarioid");

                    b.ToTable("login");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.opcoespergunta", b =>
                {
                    b.Property<int>("opcaoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("opcaoid"));

                    b.Property<int>("perguntaid")
                        .HasColumnType("integer");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("opcaoid")
                        .HasName("opcoespergunta_pkey");

                    b.HasIndex("perguntaid");

                    b.ToTable("opcoespergunta");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.perguntas", b =>
                {
                    b.Property<int>("perguntaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("perguntaid"));

                    b.Property<int>("pesquisaid")
                        .HasColumnType("integer");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("tipoperguntaid")
                        .HasColumnType("integer");

                    b.HasKey("perguntaid")
                        .HasName("perguntas_pkey");

                    b.HasIndex("pesquisaid");

                    b.HasIndex("tipoperguntaid");

                    b.ToTable("perguntas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.pesquisas", b =>
                {
                    b.Property<int>("pesquisaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pesquisaid"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("loginid")
                        .HasColumnType("integer");

                    b.Property<string>("templateJson")
                        .HasColumnType("text");

                    b.Property<int>("tipopesquisaid")
                        .HasColumnType("integer");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("pesquisaid")
                        .HasName("pesquisas_pkey");

                    b.HasIndex("loginid");

                    b.HasIndex("tipopesquisaid");

                    b.ToTable("pesquisas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.respostas", b =>
                {
                    b.Property<int>("respostaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("respostaid"));

                    b.Property<DateTime>("dataresposta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("perguntaid")
                        .HasColumnType("integer");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("respostaid")
                        .HasName("respostas_pkey");

                    b.HasIndex("perguntaid");

                    b.ToTable("respostas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipopergunta", b =>
                {
                    b.Property<int>("tipoperguntaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tipoperguntaid"));

                    b.Property<bool>("desabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("tipopergunta1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipopergunta");

                    b.HasKey("tipoperguntaid")
                        .HasName("tipopergunta_pkey");

                    b.ToTable("tipopergunta");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipopesquisa", b =>
                {
                    b.Property<int>("tipopesquisaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tipopesquisaid"));

                    b.Property<bool>("desabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("tipopesquisa1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipopesquisa");

                    b.HasKey("tipopesquisaid")
                        .HasName("tipopesquisa_pkey");

                    b.ToTable("tipopesquisa");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipousuario", b =>
                {
                    b.Property<int>("usuarioid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('usuarios_usuarioid_seq'::regclass)");

                    b.Property<string>("tipousuario1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipousuario");

                    b.HasKey("usuarioid")
                        .HasName("usuarios_pkey");

                    b.ToTable("tipousuario");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tokens", b =>
                {
                    b.Property<int>("tokenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tokenid"));

                    b.Property<DateTime>("dataexpirado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("dataregistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("tokenid")
                        .HasName("tokens_pkey");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.anexos", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.pesquisas", "pesquisa")
                        .WithMany("anexos")
                        .HasForeignKey("pesquisaid")
                        .IsRequired()
                        .HasConstraintName("anexos_pesquisaid_fkey");

                    b.Navigation("pesquisa");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.login", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.tipousuario", "tipousuario")
                        .WithMany("login")
                        .HasForeignKey("tipousuarioid")
                        .HasConstraintName("fk_login_tipousuarioid");

                    b.Navigation("tipousuario");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.opcoespergunta", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.perguntas", "pergunta")
                        .WithMany("opcoespergunta")
                        .HasForeignKey("perguntaid")
                        .IsRequired()
                        .HasConstraintName("opcoespergunta_perguntaid_fkey");

                    b.Navigation("pergunta");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.perguntas", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.pesquisas", "pesquisa")
                        .WithMany("perguntas")
                        .HasForeignKey("pesquisaid")
                        .IsRequired()
                        .HasConstraintName("perguntas_pesquisaid_fkey");

                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.tipopergunta", "tipopergunta")
                        .WithMany("perguntas")
                        .HasForeignKey("tipoperguntaid")
                        .IsRequired()
                        .HasConstraintName("perguntas_tipoperguntaid_fkey");

                    b.Navigation("pesquisa");

                    b.Navigation("tipopergunta");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.pesquisas", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.login", "login")
                        .WithMany("pesquisas")
                        .HasForeignKey("loginid")
                        .IsRequired()
                        .HasConstraintName("fk_pesquisas_loginid");

                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.tipopesquisa", "tipopesquisa")
                        .WithMany("pesquisas")
                        .HasForeignKey("tipopesquisaid")
                        .IsRequired()
                        .HasConstraintName("pesquisas_tipopesquisaid_fkey");

                    b.Navigation("login");

                    b.Navigation("tipopesquisa");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.respostas", b =>
                {
                    b.HasOne("SISTEMA_FASTSURVEY.MODEL.Models.perguntas", "pergunta")
                        .WithMany("respostas")
                        .HasForeignKey("perguntaid")
                        .IsRequired()
                        .HasConstraintName("respostas_perguntaid_fkey");

                    b.Navigation("pergunta");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.login", b =>
                {
                    b.Navigation("pesquisas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.perguntas", b =>
                {
                    b.Navigation("opcoespergunta");

                    b.Navigation("respostas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.pesquisas", b =>
                {
                    b.Navigation("anexos");

                    b.Navigation("perguntas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipopergunta", b =>
                {
                    b.Navigation("perguntas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipopesquisa", b =>
                {
                    b.Navigation("pesquisas");
                });

            modelBuilder.Entity("SISTEMA_FASTSURVEY.MODEL.Models.tipousuario", b =>
                {
                    b.Navigation("login");
                });
#pragma warning restore 612, 618
        }
    }
}
