-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Anexos"
(
    "AnexoId" integer NOT NULL DEFAULT nextval('anexos_anexoid_seq'::regclass),
    "PesquisaId" integer NOT NULL,
    "Nome" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Extensao" character varying(25) COLLATE pg_catalog."default" NOT NULL,
    "PerguntaId" integer,
    "NomeOriginal" character varying(255) COLLATE pg_catalog."default",
    "ContentType" character varying(150) COLLATE pg_catalog."default",
    "TamanhoBytes" bigint,
    "Base64Data" text COLLATE pg_catalog."default",
    CONSTRAINT anexos_pkey PRIMARY KEY ("AnexoId")
);

CREATE TABLE IF NOT EXISTS public."ExternalLogins"
(
    "ExternalLoginId" integer NOT NULL DEFAULT nextval('externallogins_externalloginid_seq'::regclass),
    "LoginId" integer NOT NULL,
    "Provider" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "ProviderUserId" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT externallogins_pkey PRIMARY KEY ("ExternalLoginId"),
    CONSTRAINT uq_provider_user UNIQUE ("Provider", "ProviderUserId")
);

CREATE TABLE IF NOT EXISTS public."Login"
(
    "LoginId" integer NOT NULL DEFAULT nextval('login_loginid_seq'::regclass),
    "Usuario" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Senha" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DataRegistro" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TipoUsuarioId" integer DEFAULT 13,
    "TipoUsuarioTexto" character varying(50) COLLATE pg_catalog."default",
    "EmailConfirmado" boolean NOT NULL DEFAULT false,
    CONSTRAINT login_pkey PRIMARY KEY ("LoginId"),
    CONSTRAINT uq_login_email UNIQUE ("Email")
);

CREATE TABLE IF NOT EXISTS public."LoginAvatar"
(
    "AvatarId" integer NOT NULL DEFAULT nextval('loginavatar_avatarid_seq'::regclass),
    "LoginId" integer NOT NULL,
    "StorageUrl" text COLLATE pg_catalog."default",
    "NomeOriginal" character varying(255) COLLATE pg_catalog."default",
    "ContentType" character varying(150) COLLATE pg_catalog."default",
    "TamanhoBytes" bigint,
    "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AtualizadoEm" timestamp with time zone,
    "Versao" integer NOT NULL DEFAULT 0,
    CONSTRAINT loginavatar_pkey PRIMARY KEY ("AvatarId"),
    CONSTRAINT uq_loginavatar_loginid UNIQUE ("LoginId")
);

CREATE TABLE IF NOT EXISTS public."OpcoesPergunta"
(
    "OpcaoId" integer NOT NULL DEFAULT nextval('opcoespergunta_opcaoid_seq'::regclass),
    "PerguntaId" integer NOT NULL,
    "Texto" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Correta" boolean NOT NULL DEFAULT false,
    "Ordem" integer NOT NULL DEFAULT 0,
    "Ativa" boolean NOT NULL DEFAULT true,
    CONSTRAINT opcoespergunta_pkey PRIMARY KEY ("OpcaoId")
);

CREATE TABLE IF NOT EXISTS public."ParticipantesSessao"
(
    "ParticipanteId" integer NOT NULL DEFAULT nextval('participantes_sessao_participante_id_seq'::regclass),
    "SessaoId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "NomeParticipante" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "EntrouEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SaiuEm" timestamp with time zone,
    CONSTRAINT participantes_sessao_pkey PRIMARY KEY ("ParticipanteId")
);

CREATE TABLE IF NOT EXISTS public."Pastas"
(
    "PastaId" integer NOT NULL DEFAULT nextval('pastas_pastaid_seq'::regclass),
    "Nome" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "LoginId" integer,
    CONSTRAINT pastas_pkey PRIMARY KEY ("PastaId"),
    CONSTRAINT uq_pastas_loginid_nome UNIQUE ("LoginId", "Nome")
);

CREATE TABLE IF NOT EXISTS public."Perguntas"
(
    "PerguntaId" integer NOT NULL DEFAULT nextval('perguntas_perguntaid_seq'::regclass),
    "TipoPerguntaId" integer NOT NULL,
    "PesquisaId" integer NOT NULL,
    "Texto" text COLLATE pg_catalog."default" NOT NULL,
    "TemGabarito" boolean NOT NULL DEFAULT false,
    "PermiteMultiplasSelecao" boolean NOT NULL DEFAULT false,
    "Ordem" integer NOT NULL DEFAULT 0,
    CONSTRAINT perguntas_pkey PRIMARY KEY ("PerguntaId")
);

CREATE TABLE IF NOT EXISTS public."Pesquisas"
(
    "PesquisaId" integer NOT NULL DEFAULT nextval('pesquisas_pesquisaid_seq'::regclass),
    "LoginId" integer NOT NULL,
    "TipoPesquisaId" integer NOT NULL,
    "Titulo" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Descricao" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "TemplateJson" text COLLATE pg_catalog."default" DEFAULT '[]'::text,
    "PastaId" integer,
    "DataCriacao" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DataAtualizacao" timestamp with time zone,
    "QRCodeUrl" text COLLATE pg_catalog."default",
    "TemLimitadorTempo" boolean NOT NULL DEFAULT false,
    "DataFechamento" timestamp with time zone,
    "IsInterativa" boolean NOT NULL DEFAULT false,
    "PermiteRespostasAnonimas" boolean NOT NULL DEFAULT true,
    "LimiteRespostas" integer,
    "Ativa" boolean NOT NULL DEFAULT true,
    CONSTRAINT pesquisas_pkey PRIMARY KEY ("PesquisaId")
);

CREATE TABLE IF NOT EXISTS public."Respostas"
(
    "RespostaId" integer NOT NULL DEFAULT nextval('respostas_respostaid_seq'::regclass),
    "PerguntaId" integer NOT NULL,
    "Texto" text COLLATE pg_catalog."default" NOT NULL,
    "DataResposta" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SessaoId" character varying(50) COLLATE pg_catalog."default",
    "RespostaAnonima" boolean NOT NULL DEFAULT false,
    "ParticipanteId" integer,
    CONSTRAINT "RespostasPkey" PRIMARY KEY ("RespostaId")
);

CREATE TABLE IF NOT EXISTS public."RespostasAnexos"
(
    "RespostaId" integer NOT NULL,
    "AnexoId" integer NOT NULL,
    CONSTRAINT "RespostasAnexosPkey" PRIMARY KEY ("RespostaId", "AnexoId")
);

CREATE TABLE IF NOT EXISTS public."RespostasOpcoes"
(
    "RespostaId" integer NOT NULL,
    "OpcaoId" integer NOT NULL,
    CONSTRAINT "RespostasOpcoesPkey" PRIMARY KEY ("RespostaId", "OpcaoId")
);

CREATE TABLE IF NOT EXISTS public."SessoesInterativas"
(
    "SessaoId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PesquisaId" integer NOT NULL,
    "CodigoAcesso" character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "CriadaEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IniciadaEm" timestamp with time zone,
    "FinalizadaEm" timestamp with time zone,
    "Ativa" boolean NOT NULL DEFAULT true,
    CONSTRAINT "SessoesInterativasPkey" PRIMARY KEY ("SessaoId"),
    CONSTRAINT "UqSessoesCodigo" UNIQUE ("CodigoAcesso")
);

CREATE TABLE IF NOT EXISTS public."TipoPergunta"
(
    "TipoPerguntaId" integer NOT NULL DEFAULT nextval('tipopergunta_tipoperguntaid_seq'::regclass),
    "TipoPergunta" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Desabilitado" boolean NOT NULL DEFAULT false,
    CONSTRAINT "TipoPerguntaPkey" PRIMARY KEY ("TipoPerguntaId")
);

COMMENT ON TABLE public."TipoPergunta"
    IS 'Tipos de pergunta: 1=Discursiva, 2=Objetiva, 3=Multipla Escolha';

CREATE TABLE IF NOT EXISTS public."TipoPesquisa"
(
    "TipoPesquisaId" integer NOT NULL DEFAULT nextval('tipopesquisa_tipopesquisaid_seq'::regclass),
    "TipoPesquisa" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Desabilitado" boolean NOT NULL DEFAULT false,
    CONSTRAINT "TipoPesquisaPkey" PRIMARY KEY ("TipoPesquisaId")
);

COMMENT ON TABLE public."TipoPesquisa"
    IS 'Tipos de pesquisa: 1=Pesquisa de Campo, 2=Teste';

CREATE TABLE IF NOT EXISTS public."TipoUsuario"
(
    "TipoUsuarioId" integer NOT NULL DEFAULT nextval('tipousuario_tipousuarioid_seq'::regclass),
    "TipoUsuario" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "TipoUsuarioPkey" PRIMARY KEY ("TipoUsuarioId")
);

COMMENT ON TABLE public."TipoUsuario"
    IS 'Tipos de usuário: 13=Usuário, 14=Usuário Premium, 15=Administrador';

CREATE TABLE IF NOT EXISTS public."Tokens"
(
    "TokenId" integer NOT NULL DEFAULT nextval('tokens_tokenid_seq'::regclass),
    "Token" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "DataRegistro" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DataExpirado" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP + '24:00:00'::interval),
    "LoginId" integer,
    "Finalidade" character varying(30) COLLATE pg_catalog."default",
    "UsadoEm" timestamp with time zone,
    CONSTRAINT "TokensPkey" PRIMARY KEY ("TokenId"),
    CONSTRAINT "UqTokensToken" UNIQUE ("Token")
);

ALTER TABLE IF EXISTS public."Anexos"
    ADD CONSTRAINT anexos_perguntaid_fkey FOREIGN KEY ("PerguntaId")
    REFERENCES public."Perguntas" ("PerguntaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_anexos_perguntaid
    ON public."Anexos"("PerguntaId");


ALTER TABLE IF EXISTS public."Anexos"
    ADD CONSTRAINT anexos_pesquisaid_fkey FOREIGN KEY ("PesquisaId")
    REFERENCES public."Pesquisas" ("PesquisaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_anexos_pesquisaid
    ON public."Anexos"("PesquisaId");


ALTER TABLE IF EXISTS public."ExternalLogins"
    ADD CONSTRAINT fk_externallogins_loginid FOREIGN KEY ("LoginId")
    REFERENCES public."Login" ("LoginId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_externallogins_loginid
    ON public."ExternalLogins"("LoginId");


ALTER TABLE IF EXISTS public."Login"
    ADD CONSTRAINT "FkLoginTipoUsuarioId" FOREIGN KEY ("TipoUsuarioId")
    REFERENCES public."TipoUsuario" ("TipoUsuarioId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."LoginAvatar"
    ADD CONSTRAINT fk_loginavatar_loginid FOREIGN KEY ("LoginId")
    REFERENCES public."Login" ("LoginId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_loginavatar_loginid
    ON public."LoginAvatar"("LoginId");


ALTER TABLE IF EXISTS public."OpcoesPergunta"
    ADD CONSTRAINT opcoespergunta_perguntaid_fkey FOREIGN KEY ("PerguntaId")
    REFERENCES public."Perguntas" ("PerguntaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_opcoespergunta_perguntaid
    ON public."OpcoesPergunta"("PerguntaId");


ALTER TABLE IF EXISTS public."ParticipantesSessao"
    ADD CONSTRAINT "FkParticipantesSessao" FOREIGN KEY ("SessaoId")
    REFERENCES public."SessoesInterativas" ("SessaoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Pastas"
    ADD CONSTRAINT fk_pastas_loginid FOREIGN KEY ("LoginId")
    REFERENCES public."Login" ("LoginId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Perguntas"
    ADD CONSTRAINT perguntas_pesquisaid_fkey FOREIGN KEY ("PesquisaId")
    REFERENCES public."Pesquisas" ("PesquisaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_perguntas_pesquisaid
    ON public."Perguntas"("PesquisaId");


ALTER TABLE IF EXISTS public."Perguntas"
    ADD CONSTRAINT perguntas_tipoperguntaid_fkey FOREIGN KEY ("TipoPerguntaId")
    REFERENCES public."TipoPergunta" ("TipoPerguntaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_perguntas_tipoperguntaid
    ON public."Perguntas"("TipoPerguntaId");


ALTER TABLE IF EXISTS public."Pesquisas"
    ADD CONSTRAINT fk_pesquisas_loginid FOREIGN KEY ("LoginId")
    REFERENCES public."Login" ("LoginId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_pesquisas_loginid
    ON public."Pesquisas"("LoginId");


ALTER TABLE IF EXISTS public."Pesquisas"
    ADD CONSTRAINT pesquisas_pastaid_fkey FOREIGN KEY ("PastaId")
    REFERENCES public."Pastas" ("PastaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_pesquisas_pastaid
    ON public."Pesquisas"("PastaId");


ALTER TABLE IF EXISTS public."Pesquisas"
    ADD CONSTRAINT pesquisas_tipopesquisaid_fkey FOREIGN KEY ("TipoPesquisaId")
    REFERENCES public."TipoPesquisa" ("TipoPesquisaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_pesquisas_tipopesquisa
    ON public."Pesquisas"("TipoPesquisaId");


ALTER TABLE IF EXISTS public."Respostas"
    ADD CONSTRAINT "FkRespostasParticipante" FOREIGN KEY ("ParticipanteId")
    REFERENCES public."ParticipantesSessao" ("ParticipanteId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Respostas"
    ADD CONSTRAINT "RespostasPerguntaIdFkey" FOREIGN KEY ("PerguntaId")
    REFERENCES public."Perguntas" ("PerguntaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IdxRespostasPerguntaId"
    ON public."Respostas"("PerguntaId");


ALTER TABLE IF EXISTS public."RespostasAnexos"
    ADD CONSTRAINT "RespostasAnexosAnexoIdFkey" FOREIGN KEY ("AnexoId")
    REFERENCES public."Anexos" ("AnexoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IdxRespostasAnexosAnexoId"
    ON public."RespostasAnexos"("AnexoId");


ALTER TABLE IF EXISTS public."RespostasAnexos"
    ADD CONSTRAINT "RespostasAnexosRespostaIdFkey" FOREIGN KEY ("RespostaId")
    REFERENCES public."Respostas" ("RespostaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."RespostasOpcoes"
    ADD CONSTRAINT "RespostasOpcoesOpcaoIdFkey" FOREIGN KEY ("OpcaoId")
    REFERENCES public."OpcoesPergunta" ("OpcaoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IdxRespostasOpcoesOpcaoId"
    ON public."RespostasOpcoes"("OpcaoId");


ALTER TABLE IF EXISTS public."RespostasOpcoes"
    ADD CONSTRAINT "RespostasOpcoesRespostaIdFkey" FOREIGN KEY ("RespostaId")
    REFERENCES public."Respostas" ("RespostaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IdxRespostasOpcoesRespostaId"
    ON public."RespostasOpcoes"("RespostaId");


ALTER TABLE IF EXISTS public."SessoesInterativas"
    ADD CONSTRAINT "FkSessoesPesquisa" FOREIGN KEY ("PesquisaId")
    REFERENCES public."Pesquisas" ("PesquisaId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Tokens"
    ADD CONSTRAINT "FkTokensLoginId" FOREIGN KEY ("LoginId")
    REFERENCES public."Login" ("LoginId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;