-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.anexos
(
    anexoid serial NOT NULL,
    pesquisaid integer NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    extensao character varying(25) COLLATE pg_catalog."default" NOT NULL,
    perguntaid integer,
    nomeoriginal character varying(255) COLLATE pg_catalog."default",
    contenttype character varying(150) COLLATE pg_catalog."default",
    tamanhobytes bigint,
    base64data text COLLATE pg_catalog."default",
    CONSTRAINT anexos_pkey PRIMARY KEY (anexoid)
);

CREATE TABLE IF NOT EXISTS public.login
(
    loginid serial NOT NULL,
    usuario character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dataregistro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipousuarioid integer,
    tipousuariotexto character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT login_pkey PRIMARY KEY (loginid)
);

CREATE TABLE IF NOT EXISTS public.opcoespergunta
(
    opcaoid serial NOT NULL,
    perguntaid integer NOT NULL,
    texto character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT opcoespergunta_pkey PRIMARY KEY (opcaoid)
);

CREATE TABLE IF NOT EXISTS public.perguntas
(
    perguntaid serial NOT NULL,
    tipoperguntaid integer NOT NULL,
    pesquisaid integer NOT NULL,
    texto text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perguntas_pkey PRIMARY KEY (perguntaid)
);

CREATE TABLE IF NOT EXISTS public.pesquisas
(
    pesquisaid serial NOT NULL,
    loginid integer NOT NULL,
    tipopesquisaid integer NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "TemplateJson" text COLLATE pg_catalog."default",
    CONSTRAINT pesquisas_pkey PRIMARY KEY (pesquisaid)
);

CREATE TABLE IF NOT EXISTS public.respostas
(
    respostaid serial NOT NULL,
    perguntaid integer NOT NULL,
    texto text COLLATE pg_catalog."default" NOT NULL,
    dataresposta timestamp without time zone NOT NULL,
    CONSTRAINT respostas_pkey PRIMARY KEY (respostaid)
);

CREATE TABLE IF NOT EXISTS public.tipopergunta
(
    tipoperguntaid serial NOT NULL,
    tipopergunta character varying(200) COLLATE pg_catalog."default" NOT NULL,
    desabilitado boolean NOT NULL DEFAULT false,
    CONSTRAINT tipopergunta_pkey PRIMARY KEY (tipoperguntaid)
);

CREATE TABLE IF NOT EXISTS public.tipopesquisa
(
    tipopesquisaid serial NOT NULL,
    tipopesquisa character varying(200) COLLATE pg_catalog."default" NOT NULL,
    desabilitado boolean NOT NULL DEFAULT false,
    CONSTRAINT tipopesquisa_pkey PRIMARY KEY (tipopesquisaid)
);

CREATE TABLE IF NOT EXISTS public.tipousuario
(
    usuarioid integer NOT NULL DEFAULT nextval('usuarios_usuarioid_seq'::regclass),
    tipousuario character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (usuarioid)
);

CREATE TABLE IF NOT EXISTS public.tokens
(
    tokenid serial NOT NULL,
    token character varying(6) COLLATE pg_catalog."default" NOT NULL,
    dataregistro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dataexpirado timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tokens_pkey PRIMARY KEY (tokenid)
);

ALTER TABLE IF EXISTS public.anexos
    ADD CONSTRAINT anexos_perguntaid_fkey FOREIGN KEY (perguntaid)
    REFERENCES public.perguntas (perguntaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.anexos
    ADD CONSTRAINT anexos_pesquisaid_fkey FOREIGN KEY (pesquisaid)
    REFERENCES public.pesquisas (pesquisaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.login
    ADD CONSTRAINT fk_login_tipousuarioid FOREIGN KEY (tipousuarioid)
    REFERENCES public.tipousuario (usuarioid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.opcoespergunta
    ADD CONSTRAINT opcoespergunta_perguntaid_fkey FOREIGN KEY (perguntaid)
    REFERENCES public.perguntas (perguntaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas
    ADD CONSTRAINT perguntas_pesquisaid_fkey FOREIGN KEY (pesquisaid)
    REFERENCES public.pesquisas (pesquisaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perguntas
    ADD CONSTRAINT perguntas_tipoperguntaid_fkey FOREIGN KEY (tipoperguntaid)
    REFERENCES public.tipopergunta (tipoperguntaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pesquisas
    ADD CONSTRAINT fk_pesquisas_loginid FOREIGN KEY (loginid)
    REFERENCES public.login (loginid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pesquisas
    ADD CONSTRAINT pesquisas_tipopesquisaid_fkey FOREIGN KEY (tipopesquisaid)
    REFERENCES public.tipopesquisa (tipopesquisaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.respostas
    ADD CONSTRAINT respostas_perguntaid_fkey FOREIGN KEY (perguntaid)
    REFERENCES public.perguntas (perguntaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;